spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/softwareprojectmanagementsystem
spring.datasource.username=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Enable the docs explicitly
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# If you want to see exactly what is failing, enable debug logs
logging.level.org.springdoc=DEBUG
